title = "neroices"
baseURL = 'https://slce.moe/'
languageCode = 'en-us'
theme = "hugo-blog-awesome"
defaultContentLanguage = "en-us"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2
		endLevel = 4
		ordered = false

  [menu]
  [[menu.main]]
    pageRef="/"
    name = '~/'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'posts/'
    url = '/posts/'
    weight = 20

[params]
  sitename = "neroices"
  defaultColor = "dark"
  description = "Neroices's home."
  mainSections = ['posts']
  toc = true
  tocOpen = false
  goToTop = true
  rssFeedDescription = "summary"

[params.author]
  avatar = "avatar.png"
  intro = "~ whoami"
  name = "neroices"
  description = "Stuck in the codeverse, but not exactly living for it. I figure things out, but mostly while chilling with games. Not a techie at heart, but gotta keep learning, right? Balancing tech with my other side, whatever that is."

[params.webmanifest]
  name = "neroices"
  short_name = "nice"
  start_url = "/"
  theme_color = "#434648"
  background_color = "#fff"
  display = "standalone"

[params.browserconfig]
  TileColor = "#2d89ef"

[[params.socialIcons]]
name = "github"
url = "https://github.com/neroices"

[[params.socialIcons]]
name = "gitlab"
url = "https://gitlab.com/neroices"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"